### ISSUE TITLE
indy.error.IndyError: ErrorCode.CommonInvalidState error while starting von-network

### ISSUE THREAD

**Issue by mehmetaydar** [IBM-Blockchain-Identity/indy-ssivc-tutorial#17]
Built von-network using: `./manage build` .
Getting the following error while starting it, `./manage start`

> von-web_1  | ERROR|indy::errors::indy            |                 src/errors/indy.rs:68  | Casting error to ErrorCode: Invalid library state: Unexpected SQLite error: execute returned results - did you mean to call query?
von-web_1  | _indy_loop_callback: Function returned error 112
von-web_1  | Traceback (most recent call last):
von-web_1  |   File "server.py", line 295, in <module>
von-web_1  |     loop.run_until_complete(boot())
von-web_1  |   File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
von-web_1  |     return future.result()
von-web_1  |   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
von-web_1  |     raise self._exception
von-web_1  |   File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
von-web_1  |     result = coro.throw(exc)
von-web_1  |   File "server.py", line 121, in boot
von-web_1  |     await trust_anchor.open()
von-web_1  |   File "/home/indy/.local/share/virtualenvs/server-8XoupS0v/lib/python3.5/site-packages/von_agent/agents.py", line 126, in open
von-web_1  |     await self.wallet.open()
von-web_1  |   File "/home/indy/.local/share/virtualenvs/server-8XoupS0v/lib/python3.5/site-packages/von_agent/wallet.py", line 186, in open
von-web_1  |     credentials=json.dumps(self.creds) if self.creds else None)
von-web_1  |   File "/home/indy/.local/share/virtualenvs/server-8XoupS0v/lib/python3.5/site-packages/indy/wallet.py", line 52, in create_wallet
von-web_1  |     create_wallet.cb)
von-web_1  |   File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
von-web_1  |     yield self  # This tells Task to wait for completion.
von-web_1  |   File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
von-web_1  |     future.result()
von-web_1  |   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
von-web_1  |     raise self._exception
von-web_1  | indy.error.IndyError: ErrorCode.CommonInvalidState

> 

http://ip:9000/ and http://ip:9000/ are not coming up.

**Comment by brycecurtis** [comment]
What OS are you using?  Based upon the url http://ip:9000, I would guess that your host ip isn't being set correctly.  You can set the environment variable APPLICATION_URL to your host IP (not the loopback of 127.0.0.1).  Then do build and start again.

**Comment by mehmetaydar** [comment]
@brycecurtis where can I set the environment variable APPLICATION_URL to my host IP?

**Comment by mehmetaydar** [comment]
@brycecurtis I am using Ubuntu. I am trying to access it from my windows machine. I am able to run the von-network, TheOrgBook, and permitify from the latest bcgov repositories. However I am unable to make this tutorial work. It would be nice if you run this tutorial by deriving from the latest bcgov repositories, or provide the instructions about how to do it. Best.

**Comment by brycecurtis** [comment]
@mehmetaydar This tutorial is provided as a learning experience and was based upon the latest bcgov repositories at the time it was written.  As you know, the bcgov code has changed significantly since this tutorial.  There are no plans to update the tutorial, and at some point we will mark as deprecated.  However, we do have a live version of the tutorial running at https://indyworld.vcreds.org if you can't get it running locally.
