### ISSUE TITLE
Another TheOrgBook/docker$ ./manage.sh build fails

### ISSUE THREAD

**Issue by riceman33** [IBM-Blockchain-Identity/indy-ssivc-tutorial#27]
Looks like same error reported recently in a comment on the closed issue #5 

> tob-web@0.0.1 postinstall /opt/app-root/src
> ng build --prod --base-href ${NG_BASE_HREF:-/} ${NG_BUILD_FLAGS:-} && cp dist/themes/_active/index.html dist/index.html

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/opt/app-root/src/src'
ERROR in Error: Error encountered resolving symbol values statically. Could not resolve localize-router relative to /opt/app-root/src/src/app/app.module.ts., resolving symbol AppModule in /opt/app-root/src/src/app/app.module.ts, resolving symbol AppModule in /opt/app-root/src/src/app/app.module.ts, resolving symbol AppModule in /opt/app-root/src/src/app/app.module.ts
    at Error (native)
    at syntaxError (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
Date: 2019-01-18T11:38:47.020Z
Hash: 4b2d3c942ddbc7fbd103
Time: 10618ms
chunk {0} polyfills.3812c0cf314a37f1c67a.bundle.js (polyfills) 68.4 kB [initial] [rendered]
chunk {1} main.d4e3ea57bd9f031aba88.bundle.js (main) 434 bytes [initial] [rendered]
chunk {2} styles.bd7c2783ce79f1c86e3d.bundle.css (styles) 1.61 kB [initial] [rendered]
chunk {3} vendor.44e30b54a081b139a9e3.bundle.js (vendor) 208 kB [initial] [rendered]
chunk {4} inline.31e1fb380eb7cf3d75b1.bundle.js (inline) 798 bytes [entry] [rendered]
    at NgModuleResolver.resolve (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:14750:70)
    at CompileMetadataResolver.getNgModuleMetadata (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:15402:60)
    at addNgModule (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:24268:58)
    at /opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:24279:14
    at Array.forEach (native)
    at _createNgModules (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:24278:26)
    at analyzeNgModules (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:24153:14)
    at analyzeAndValidateNgModules (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:24163:35)
    at AotCompiler.analyzeModulesAsync (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:23797:46)
    at CodeGenerator.codegen (/opt/app-root/src/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (/opt/app-root/src/node_modules/@angular/compiler-cli/src/ngtools_api.js:73:30)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN localize-router-http-loader@0.0.3 requires a peer of localize-router@>=1.0.0-alpha.1 but none was installed.
npm WARN localize-router@2.0.0-RC.2 requires a peer of @angular/core@>=6.0.0 but none was installed.
npm WARN localize-router@2.0.0-RC.2 requires a peer of @angular/common@>=6.0.0 but none was installed.
npm WARN localize-router@2.0.0-RC.2 requires a peer of @angular/router@>=6.0.0 but none was installed.
npm WARN localize-router@2.0.0-RC.2 requires a peer of rxjs@^6.0.0 but none was installed.
npm WARN localize-router@2.0.0-RC.2 requires a peer of @ngx-translate/core@>=10.0.0 but none was installed.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none was installed.
npm ERR! Linux 4.9.93-linuxkit-aufs
npm ERR! argv "/opt/rh/rh-nodejs6/root/usr/bin/node" "/opt/rh/rh-nodejs6/root/usr/bin/npm" "install"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! tob-web@0.0.1 postinstall: `ng build --prod --base-href ${NG_BASE_HREF:-/} ${NG_BUILD_FLAGS:-} && cp dist/themes/_active/index.html dist/index.html`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tob-web@0.0.1 postinstall script 'ng build --prod --base-href ${NG_BASE_HREF:-/} ${NG_BUILD_FLAGS:-} && cp dist/themes/_active/index.html dist/index.html'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tob-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng build --prod --base-href ${NG_BASE_HREF:-/} ${NG_BUILD_FLAGS:-} && cp dist/themes/_active/index.html dist/index.html
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tob-web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tob-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/app-root/src/npm-debug.log
Build failed
ERROR: An error occurred: non-zero (13) exit code from centos/nodejs-6-centos7:6

**Comment by kagile** [comment]
I am getting the same:

```
> tob-web@0.0.1 postinstall /opt/app-root/src
> ng build --prod --base-href ${NG_BASE_HREF:-/} ${NG_BUILD_FLAGS:-} && cp dist/themes/_active/index.html dist/index.html

Date: 2019-01-22T07:44:43.495Z
Hash: 4b2d3c942ddbc7fbd103
Time: 7727ms
chunk {0} polyfills.3812c0cf314a37f1c67a.bundle.js (polyfills) 68.4 kB [initial] [rendered]
chunk {1} main.d4e3ea57bd9f031aba88.bundle.js (main) 434 bytes [initial] [rendered]
chunk {2} styles.bd7c2783ce79f1c86e3d.bundle.css (styles) 1.61 kB [initial] [rendered]
chunk {3} vendor.44e30b54a081b139a9e3.bundle.js (vendor) 208 kB [initial] [rendered]
chunk {4} inline.31e1fb380eb7cf3d75b1.bundle.js (inline) 798 bytes [entry] [rendered]

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/opt/app-root/src/src'
ERROR in Error: Error encountered resolving symbol values statically. Could not resolve localize-router relative to /opt/app-root/src/src/app/app.module.ts., resolving symbol AppModule in /opt/app-root/src/src/app/app.module.ts, resolving symbol AppModule in /opt/app-root/src/src/app/app.module.ts, resolving symbol AppModule in /opt/app-root/src/src/app/app.module.ts
    at Error (native)
    at syntaxError (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at NgModuleResolver.resolve (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:14750:70)
    at CompileMetadataResolver.getNgModuleMetadata (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:15402:60)
    at addNgModule (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:24268:58)
    at /opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:24279:14
    at Array.forEach (native)
    at _createNgModules (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:24278:26)
    at analyzeNgModules (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:24153:14)
    at analyzeAndValidateNgModules (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:24163:35)
    at AotCompiler.analyzeModulesAsync (/opt/app-root/src/node_modules/@angular/compiler/bundles/compiler.umd.js:23797:46)
    at CodeGenerator.codegen (/opt/app-root/src/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (/opt/app-root/src/node_modules/@angular/compiler-cli/src/ngtools_api.js:73:30)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN localize-router-http-loader@0.0.3 requires a peer of localize-router@>=1.0.0-alpha.1 but none was installed.
npm WARN localize-router@2.0.0-RC.2 requires a peer of @angular/core@>=6.0.0 but none was installed.
npm WARN localize-router@2.0.0-RC.2 requires a peer of @angular/common@>=6.0.0 but none was installed.
npm WARN localize-router@2.0.0-RC.2 requires a peer of @angular/router@>=6.0.0 but none was installed.
npm WARN localize-router@2.0.0-RC.2 requires a peer of rxjs@^6.0.0 but none was installed.
npm WARN localize-router@2.0.0-RC.2 requires a peer of @ngx-translate/core@>=10.0.0 but none was installed.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none was installed.
npm ERR! Linux 4.4.0-141-generic
npm ERR! argv "/opt/rh/rh-nodejs6/root/usr/bin/node" "/opt/rh/rh-nodejs6/root/usr/bin/npm" "install"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! tob-web@0.0.1 postinstall: `ng build --prod --base-href ${NG_BASE_HREF:-/} ${NG_BUILD_FLAGS:-} && cp dist/themes/_active/index.html dist/index.html`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tob-web@0.0.1 postinstall script 'ng build --prod --base-href ${NG_BASE_HREF:-/} ${NG_BUILD_FLAGS:-} && cp dist/themes/_active/index.html dist/index.html'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tob-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng build --prod --base-href ${NG_BASE_HREF:-/} ${NG_BUILD_FLAGS:-} && cp dist/themes/_active/index.html dist/index.html
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tob-web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tob-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/app-root/src/npm-debug.log
Build failed
ERROR: An error occurred: non-zero (13) exit code from centos/nodejs-6-centos7:6
```

**Comment by riceman33** [comment]
changing localize-router dependency in package.json got me past this error:

```"localize-router": "<2.0.0-RC.1",```

**Comment by kpratihast** [comment]
@riceman33 Can you please point out in which file (manage.sh / docker-compose.yml / or somewhere in tob-api folder) you made the below changes ?

> changing localize-router dependency in package.json got me past this error:
> 
> `"localize-router": "<2.0.0-RC.1",`

**Comment by riceman33** [comment]
TheOrgBook/tob-web/package.json. I replaced the existing line 
```"localize-router": "git+https://github.com/cywolf/localize-router.git",```

**Comment by doyajii1** [comment]
On Osx, I faced following:
1. Although build went through with above fix, I saw following errors while building TheOrgBook:
"error: Unable to load docker config: json: cannot unmarshal string into Go value of type docker.dockerConfig"
2. I'm not sure if above problem caused this but I couldn't see "register person" button on the "http://localhost:8080/" demo page

**Comment by Igogrek** [comment]
I have also faced the same issue and even though the fix does indeed work, it does not make actual web app working - seems that routing is broken after all. See #33 (there's a potential solution there)
