### ISSUE TITLE
cannot open client HELLO -- wrong server key?

### ISSUE THREAD

**Issue by aTravelingN3rd** [IBM-Blockchain-Identity/indy-ssivc-tutorial#28]
docker-compose version 1.23.1, build b02f1306
Docker version 18.09.1, build 4c52b90

Does someone know how to resolve this issue, one of my guess would be do set IP and IPS manually in te Dockerfile but I don't know what to add there.

WARNING: The IP variable is not set. Defaulting to a blank string.
WARNING: The IPS variable is not set. Defaulting to a blank string.
Creating von_node4_1_6fa17919a466 ... done
Creating von_node1_1_5476b390308f ... done
Creating von_node2_1_4a9d0ef05463 ... done
Creating von_node3_1_fb60e3651b93 ... done
Creating von_von-web_1_e7c2cd2e1876 ... done
Attaching to von_node4_1_8a0db220c2a0, von_node1_1_5607204968b3, von_node3_1_93ef0a741eb2, von_node2_1_862571c6cde1, von_von-web_1_9cac5775c7b9
node4_1_8a0db220c2a0 | Ledger exists - using...
node4_1_8a0db220c2a0 | start_indy_node Node4 9707 9708
node4_1_8a0db220c2a0 | 2019-01-24 10:56:41,137 | DEBUG    | __init__.py          (60) | register | Registered VCS backend: git
node4_1_8a0db220c2a0 | 2019-01-24 10:56:41,162 | DEBUG    | __init__.py          (60) | register | Registered VCS backend: hg
node4_1_8a0db220c2a0 | 2019-01-24 10:56:41,224 | DEBUG    | __init__.py          (60) | register | Registered VCS backend: svn
node4_1_8a0db220c2a0 | 2019-01-24 10:56:41,225 | DEBUG    | __init__.py          (60) | register | Registered VCS backend: bzr
node4_1_8a0db220c2a0 | 2019-01-24 10:56:42,879 | DEBUG    | selector_events.py   (53) | __init__ | Using selector: EpollSelector
node4_1_8a0db220c2a0 | 2019-01-24 10:56:42,904 | DEBUG    | ledger.py            (201) | start | Starting ledger...
node4_1_8a0db220c2a0 | 2019-01-24 10:56:42,916 | DEBUG    | ledger.py            (67) | recoverTree | Recovering tree from transaction log
node4_1_8a0db220c2a0 | 2019-01-24 10:56:42,948 | DEBUG    | ledger.py            (82) | recoverTree | Recovered tree in 0.032732644001953304 seconds
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,016 | DEBUG    | ledger.py            (201) | start | Starting ledger...
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,028 | DEBUG    | ledger.py            (67) | recoverTree | Recovering tree from transaction log
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,060 | DEBUG    | ledger.py            (82) | recoverTree | Recovered tree in 0.03139139600170893 seconds
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,071 | INFO     | node.py              (2636) | initStateFromLedger | Node4 found state to be empty, recreating from ledger
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,093 | INFO     | node.py              (786) | _create_bls_bft | BLS: BLS Signatures will be used for Node Node4
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,106 | INFO     | node.py              (2636) | initStateFromLedger | Node4 found state to be empty, recreating from ledger
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,108 | INFO     | node.py              (612) | setPoolParams | Node4 updated its pool parameters: f 0, totalNodes 1, allNodeNames {'Node4'}, requiredNumberOfInstances 1, minimumNodes 1, quorums {'bls_signatures': Quorum(1), 'propagate': Quorum(1), 'observer_data': Quorum(1), 'prepare': Quorum(0), 'view_change_done': Quorum(1), 'election': Quorum(1), 'propagate_primary': Quorum(1), 'reply': Quorum(1), 'same_consistency_proof': Quorum(1), 'view_change': Quorum(1), 'commit': Quorum(1), 'consistency_proof': Quorum(1), 'f': 0, 'checkpoint': Quorum(0), 'timestamp': Quorum(1), 'ledger_status': Quorum(0)}
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,235 | INFO     | plugin_loader.py     (118) | _load | plugin FirebaseStatsConsumer successfully loaded from module plugin_firebase_stats_consumer
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,236 | DISPLAY  | replicas.py          (41) | grow | Node4 added replica Node4:0 to instance 0 (master)
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,237 | DEBUG    | plugin_helper.py     (23) | loadPlugins | Plugin loading started to load plugins from plugins_dir: /var/lib/indy/plugins
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,237 | DEBUG    | plugin_helper.py     (63) | loadPlugins | Total plugins loaded from plugins_dir /var/lib/indy/plugins are : 0
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,285 | DEBUG    | ledger.py            (201) | start | Starting ledger...
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,303 | DEBUG    | ledger.py            (67) | recoverTree | Recovering tree from transaction log
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,343 | DEBUG    | ledger.py            (82) | recoverTree | Recovered tree in 0.04053984500205843 seconds
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,374 | INFO     | node.py              (2636) | initStateFromLedger | Node4 found state to be empty, recreating from ledger
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,374 | DEBUG    | ledger.py            (199) | start | Ledger already started.
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,375 | DEBUG    | ledger.py            (199) | start | Ledger already started.
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,375 | DEBUG    | ledger.py            (199) | start | Ledger already started.
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,376 | DEBUG    | authenticator.py     (31) | start | Starting ZAP at inproc://zeromq.zap.1
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,376 | DEBUG    | base.py              (72) | allow | Allowing 0.0.0.0
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,377 | DEBUG    | base.py              (112) | configure_curve | Configure curve: *[/var/lib/indy/sandbox/keys/Node4/public_keys]
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,387 | INFO     | stacks.py            (84) | start | CONNECTION: Node4 listening for other nodes at 0.0.0.0:9707
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,389 | DEBUG    | authenticator.py     (31) | start | Starting ZAP at inproc://zeromq.zap.2
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,389 | DEBUG    | base.py              (72) | allow | Allowing 0.0.0.0
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,389 | DEBUG    | base.py              (112) | configure_curve | Configure curve: *[*]
node4_1_8a0db220c2a0 | 2019-01-24 10:56:43,391 | INFO     | node.py              (853) | start | Node4 first time running...
node3_1_93ef0a741eb2 | Ledger exists - using...
node3_1_93ef0a741eb2 | start_indy_node Node3 9705 9706
von-web_1_9cac5775c7b9 | Ledger exists - using...
node2_1_862571c6cde1 | Ledger exists - using...
node2_1_862571c6cde1 | start_indy_node Node2 9703 9704
node1_1_5607204968b3 | Ledger exists - using...
node1_1_5607204968b3 | start_indy_node Node1 9701 9702
node1_1_5607204968b3 | 2019-01-24 10:56:42,527 | DEBUG    | __init__.py          (60) | register | Registered VCS backend: git
node1_1_5607204968b3 | 2019-01-24 10:56:42,547 | DEBUG    | __init__.py          (60) | register | Registered VCS backend: hg
node1_1_5607204968b3 | 2019-01-24 10:56:42,606 | DEBUG    | __init__.py          (60) | register | Registered VCS backend: svn
node1_1_5607204968b3 | 2019-01-24 10:56:42,607 | DEBUG    | __init__.py          (60) | register | Registered VCS backend: bzr
node1_1_5607204968b3 | 2019-01-24 10:56:44,066 | DEBUG    | selector_events.py   (53) | __init__ | Using selector: EpollSelector
node1_1_5607204968b3 | 2019-01-24 10:56:44,094 | DEBUG    | ledger.py            (201) | start | Starting ledger...
node1_1_5607204968b3 | 2019-01-24 10:56:44,111 | DEBUG    | ledger.py            (67) | recoverTree | Recovering tree from transaction log
node1_1_5607204968b3 | 2019-01-24 10:56:44,149 | DEBUG    | ledger.py            (82) | recoverTree | Recovered tree in 0.037827896001545014 seconds
node1_1_5607204968b3 | 2019-01-24 10:56:44,213 | DEBUG    | ledger.py            (201) | start | Starting ledger...
node1_1_5607204968b3 | 2019-01-24 10:56:44,232 | DEBUG    | ledger.py            (67) | recoverTree | Recovering tree from transaction log
node1_1_5607204968b3 | 2019-01-24 10:56:44,275 | DEBUG    | ledger.py            (82) | recoverTree | Recovered tree in 0.04375988299943856 seconds
node1_1_5607204968b3 | 2019-01-24 10:56:44,292 | INFO     | node.py              (2636) | initStateFromLedger | Node1 found state to be empty, recreating from ledger
node1_1_5607204968b3 | 2019-01-24 10:56:44,317 | INFO     | node.py              (786) | _create_bls_bft | BLS: BLS Signatures will be used for Node Node1
node1_1_5607204968b3 | 2019-01-24 10:56:44,329 | INFO     | node.py              (2636) | initStateFromLedger | Node1 found state to be empty, recreating from ledger
node1_1_5607204968b3 | 2019-01-24 10:56:44,332 | INFO     | node.py              (612) | setPoolParams | Node1 updated its pool parameters: f 0, totalNodes 1, allNodeNames {'Node1'}, requiredNumberOfInstances 1, minimumNodes 1, quorums {'propagate': Quorum(1), 'timestamp': Quorum(1), 'prepare': Quorum(0), 'bls_signatures': Quorum(1), 'same_consistency_proof': Quorum(1), 'observer_data': Quorum(1), 'view_change': Quorum(1), 'consistency_proof': Quorum(1), 'election': Quorum(1), 'f': 0, 'ledger_status': Quorum(0), 'checkpoint': Quorum(0), 'propagate_primary': Quorum(1), 'commit': Quorum(1), 'view_change_done': Quorum(1), 'reply': Quorum(1)}
node3_1_93ef0a741eb2 | 2019-01-24 10:56:44,406 | DEBUG    | __init__.py          (60) | register | Registered VCS backend: git
node1_1_5607204968b3 | 2019-01-24 10:56:44,410 | INFO     | plugin_loader.py     (118) | _load | plugin FirebaseStatsConsumer successfully loaded from module plugin_firebase_stats_consumer
node1_1_5607204968b3 | 2019-01-24 10:56:44,412 | DISPLAY  | replicas.py          (41) | grow | Node1 added replica Node1:0 to instance 0 (master)
node1_1_5607204968b3 | 2019-01-24 10:56:44,413 | DEBUG    | plugin_helper.py     (23) | loadPlugins | Plugin loading started to load plugins from plugins_dir: /var/lib/indy/plugins
node1_1_5607204968b3 | 2019-01-24 10:56:44,413 | DEBUG    | plugin_helper.py     (63) | loadPlugins | Total plugins loaded from plugins_dir /var/lib/indy/plugins are : 0
node3_1_93ef0a741eb2 | 2019-01-24 10:56:44,424 | DEBUG    | __init__.py          (60) | register | Registered VCS backend: hg
node1_1_5607204968b3 | 2019-01-24 10:56:44,449 | DEBUG    | ledger.py            (201) | start | Starting ledger...
node1_1_5607204968b3 | 2019-01-24 10:56:44,460 | DEBUG    | ledger.py            (67) | recoverTree | Recovering tree from transaction log
node3_1_93ef0a741eb2 | 2019-01-24 10:56:44,470 | DEBUG    | __init__.py          (60) | register | Registered VCS backend: svn
node3_1_93ef0a741eb2 | 2019-01-24 10:56:44,471 | DEBUG    | __init__.py          (60) | register | Registered VCS backend: bzr
node1_1_5607204968b3 | 2019-01-24 10:56:44,490 | DEBUG    | ledger.py            (82) | recoverTree | Recovered tree in 0.03003599099974963 seconds
node1_1_5607204968b3 | 2019-01-24 10:56:44,503 | INFO     | node.py              (2636) | initStateFromLedger | Node1 found state to be empty, recreating from ledger
node1_1_5607204968b3 | 2019-01-24 10:56:44,506 | DEBUG    | ledger.py            (199) | start | Ledger already started.
node1_1_5607204968b3 | 2019-01-24 10:56:44,506 | DEBUG    | ledger.py            (199) | start | Ledger already started.
node1_1_5607204968b3 | 2019-01-24 10:56:44,507 | DEBUG    | ledger.py            (199) | start | Ledger already started.
node1_1_5607204968b3 | 2019-01-24 10:56:44,508 | DEBUG    | authenticator.py     (31) | start | Starting ZAP at inproc://zeromq.zap.1
node1_1_5607204968b3 | 2019-01-24 10:56:44,508 | DEBUG    | base.py              (72) | allow | Allowing 0.0.0.0
node1_1_5607204968b3 | 2019-01-24 10:56:44,508 | DEBUG    | base.py              (112) | configure_curve | Configure curve: *[/var/lib/indy/sandbox/keys/Node1/public_keys]
node1_1_5607204968b3 | 2019-01-24 10:56:44,510 | INFO     | stacks.py            (84) | start | CONNECTION: Node1 listening for other nodes at 0.0.0.0:9701
node1_1_5607204968b3 | 2019-01-24 10:56:44,510 | DEBUG    | authenticator.py     (31) | start | Starting ZAP at inproc://zeromq.zap.2
node1_1_5607204968b3 | 2019-01-24 10:56:44,511 | DEBUG    | base.py              (72) | allow | Allowing 0.0.0.0
node1_1_5607204968b3 | 2019-01-24 10:56:44,511 | DEBUG    | base.py              (112) | configure_curve | Configure curve: *[*]
node1_1_5607204968b3 | 2019-01-24 10:56:44,513 | INFO     | node.py              (853) | start | Node1 first time running...
node2_1_862571c6cde1 | 2019-01-24 10:56:45,240 | DEBUG    | __init__.py          (60) | register | Registered VCS backend: git
node2_1_862571c6cde1 | 2019-01-24 10:56:45,257 | DEBUG    | __init__.py          (60) | register | Registered VCS backend: hg
node2_1_862571c6cde1 | 2019-01-24 10:56:45,305 | DEBUG    | __init__.py          (60) | register | Registered VCS backend: svn
node2_1_862571c6cde1 | 2019-01-24 10:56:45,305 | DEBUG    | __init__.py          (60) | register | Registered VCS backend: bzr
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,445 | DEBUG    | selector_events.py   (53) | __init__ | Using selector: EpollSelector
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,476 | DEBUG    | ledger.py            (201) | start | Starting ledger...
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,488 | DEBUG    | ledger.py            (67) | recoverTree | Recovering tree from transaction log
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,524 | DEBUG    | ledger.py            (82) | recoverTree | Recovered tree in 0.03575115900093806 seconds
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,568 | DEBUG    | ledger.py            (201) | start | Starting ledger...
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,580 | DEBUG    | ledger.py            (67) | recoverTree | Recovering tree from transaction log
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,609 | DEBUG    | ledger.py            (82) | recoverTree | Recovered tree in 0.029137293000530917 seconds
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,620 | INFO     | node.py              (2636) | initStateFromLedger | Node3 found state to be empty, recreating from ledger
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,635 | INFO     | node.py              (786) | _create_bls_bft | BLS: BLS Signatures will be used for Node Node3
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,647 | INFO     | node.py              (2636) | initStateFromLedger | Node3 found state to be empty, recreating from ledger
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,649 | INFO     | node.py              (612) | setPoolParams | Node3 updated its pool parameters: f 0, totalNodes 1, allNodeNames {'Node3'}, requiredNumberOfInstances 1, minimumNodes 1, quorums {'prepare': Quorum(0), 'election': Quorum(1), 'commit': Quorum(1), 'checkpoint': Quorum(0), 'view_change': Quorum(1), 'observer_data': Quorum(1), 'propagate_primary': Quorum(1), 'same_consistency_proof': Quorum(1), 'view_change_done': Quorum(1), 'bls_signatures': Quorum(1), 'timestamp': Quorum(1), 'f': 0, 'reply': Quorum(1), 'consistency_proof': Quorum(1), 'propagate': Quorum(1), 'ledger_status': Quorum(0)}
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,726 | INFO     | plugin_loader.py     (118) | _load | plugin FirebaseStatsConsumer successfully loaded from module plugin_firebase_stats_consumer
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,728 | DISPLAY  | replicas.py          (41) | grow | Node3 added replica Node3:0 to instance 0 (master)
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,728 | DEBUG    | plugin_helper.py     (23) | loadPlugins | Plugin loading started to load plugins from plugins_dir: /var/lib/indy/plugins
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,728 | DEBUG    | plugin_helper.py     (63) | loadPlugins | Total plugins loaded from plugins_dir /var/lib/indy/plugins are : 0
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,762 | DEBUG    | ledger.py            (201) | start | Starting ledger...
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,774 | DEBUG    | ledger.py            (67) | recoverTree | Recovering tree from transaction log
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,805 | DEBUG    | ledger.py            (82) | recoverTree | Recovered tree in 0.03139743900101166 seconds
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,820 | INFO     | node.py              (2636) | initStateFromLedger | Node3 found state to be empty, recreating from ledger
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,821 | DEBUG    | ledger.py            (199) | start | Ledger already started.
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,821 | DEBUG    | ledger.py            (199) | start | Ledger already started.
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,821 | DEBUG    | ledger.py            (199) | start | Ledger already started.
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,822 | DEBUG    | authenticator.py     (31) | start | Starting ZAP at inproc://zeromq.zap.1
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,822 | DEBUG    | base.py              (72) | allow | Allowing 0.0.0.0
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,822 | DEBUG    | base.py              (112) | configure_curve | Configure curve: *[/var/lib/indy/sandbox/keys/Node3/public_keys]
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,823 | INFO     | stacks.py            (84) | start | CONNECTION: Node3 listening for other nodes at 0.0.0.0:9705
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,823 | DEBUG    | authenticator.py     (31) | start | Starting ZAP at inproc://zeromq.zap.2
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,823 | DEBUG    | base.py              (72) | allow | Allowing 0.0.0.0
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,824 | DEBUG    | base.py              (112) | configure_curve | Configure curve: *[*]
node3_1_93ef0a741eb2 | 2019-01-24 10:56:45,825 | INFO     | node.py              (853) | start | Node3 first time running...
node2_1_862571c6cde1 | 2019-01-24 10:56:46,244 | DEBUG    | selector_events.py   (53) | __init__ | Using selector: EpollSelector
node2_1_862571c6cde1 | 2019-01-24 10:56:46,272 | DEBUG    | ledger.py            (201) | start | Starting ledger...
node2_1_862571c6cde1 | 2019-01-24 10:56:46,287 | DEBUG    | ledger.py            (67) | recoverTree | Recovering tree from transaction log
node2_1_862571c6cde1 | 2019-01-24 10:56:46,326 | DEBUG    | ledger.py            (82) | recoverTree | Recovered tree in 0.03936544899988803 seconds
node2_1_862571c6cde1 | 2019-01-24 10:56:46,380 | DEBUG    | ledger.py            (201) | start | Starting ledger...
node2_1_862571c6cde1 | 2019-01-24 10:56:46,394 | DEBUG    | ledger.py            (67) | recoverTree | Recovering tree from transaction log
node2_1_862571c6cde1 | 2019-01-24 10:56:46,434 | DEBUG    | ledger.py            (82) | recoverTree | Recovered tree in 0.040256519001559354 seconds
node2_1_862571c6cde1 | 2019-01-24 10:56:46,450 | INFO     | node.py              (2636) | initStateFromLedger | Node2 found state to be empty, recreating from ledger
node2_1_862571c6cde1 | 2019-01-24 10:56:46,477 | INFO     | node.py              (786) | _create_bls_bft | BLS: BLS Signatures will be used for Node Node2
node2_1_862571c6cde1 | 2019-01-24 10:56:46,496 | INFO     | node.py              (2636) | initStateFromLedger | Node2 found state to be empty, recreating from ledger
node2_1_862571c6cde1 | 2019-01-24 10:56:46,510 | INFO     | node.py              (612) | setPoolParams | Node2 updated its pool parameters: f 0, totalNodes 1, allNodeNames {'Node2'}, requiredNumberOfInstances 1, minimumNodes 1, quorums {'view_change': Quorum(1), 'checkpoint': Quorum(0), 'bls_signatures': Quorum(1), 'same_consistency_proof': Quorum(1), 'prepare': Quorum(0), 'f': 0, 'propagate': Quorum(1), 'propagate_primary': Quorum(1), 'reply': Quorum(1), 'view_change_done': Quorum(1), 'commit': Quorum(1), 'ledger_status': Quorum(0), 'election': Quorum(1), 'timestamp': Quorum(1), 'consistency_proof': Quorum(1), 'observer_data': Quorum(1)}
node2_1_862571c6cde1 | 2019-01-24 10:56:46,590 | INFO     | plugin_loader.py     (118) | _load | plugin FirebaseStatsConsumer successfully loaded from module plugin_firebase_stats_consumer
node2_1_862571c6cde1 | 2019-01-24 10:56:46,592 | DISPLAY  | replicas.py          (41) | grow | Node2 added replica Node2:0 to instance 0 (master)
node2_1_862571c6cde1 | 2019-01-24 10:56:46,592 | DEBUG    | plugin_helper.py     (23) | loadPlugins | Plugin loading started to load plugins from plugins_dir: /var/lib/indy/plugins
node2_1_862571c6cde1 | 2019-01-24 10:56:46,592 | DEBUG    | plugin_helper.py     (63) | loadPlugins | Total plugins loaded from plugins_dir /var/lib/indy/plugins are : 0
node2_1_862571c6cde1 | 2019-01-24 10:56:46,626 | DEBUG    | ledger.py            (201) | start | Starting ledger...
node2_1_862571c6cde1 | 2019-01-24 10:56:46,637 | DEBUG    | ledger.py            (67) | recoverTree | Recovering tree from transaction log
node2_1_862571c6cde1 | 2019-01-24 10:56:46,668 | DEBUG    | ledger.py            (82) | recoverTree | Recovered tree in 0.030970766001701122 seconds
node2_1_862571c6cde1 | 2019-01-24 10:56:46,687 | INFO     | node.py              (2636) | initStateFromLedger | Node2 found state to be empty, recreating from ledger
node2_1_862571c6cde1 | 2019-01-24 10:56:46,689 | DEBUG    | ledger.py            (199) | start | Ledger already started.
node2_1_862571c6cde1 | 2019-01-24 10:56:46,689 | DEBUG    | ledger.py            (199) | start | Ledger already started.
node2_1_862571c6cde1 | 2019-01-24 10:56:46,690 | DEBUG    | ledger.py            (199) | start | Ledger already started.
node2_1_862571c6cde1 | 2019-01-24 10:56:46,692 | DEBUG    | authenticator.py     (31) | start | Starting ZAP at inproc://zeromq.zap.1
node2_1_862571c6cde1 | 2019-01-24 10:56:46,693 | DEBUG    | base.py              (72) | allow | Allowing 0.0.0.0
node2_1_862571c6cde1 | 2019-01-24 10:56:46,693 | DEBUG    | base.py              (112) | configure_curve | Configure curve: *[/var/lib/indy/sandbox/keys/Node2/public_keys]
node2_1_862571c6cde1 | 2019-01-24 10:56:46,697 | INFO     | stacks.py            (84) | start | CONNECTION: Node2 listening for other nodes at 0.0.0.0:9703
node2_1_862571c6cde1 | 2019-01-24 10:56:46,698 | DEBUG    | authenticator.py     (31) | start | Starting ZAP at inproc://zeromq.zap.2
node2_1_862571c6cde1 | 2019-01-24 10:56:46,699 | DEBUG    | base.py              (72) | allow | Allowing 0.0.0.0
node2_1_862571c6cde1 | 2019-01-24 10:56:46,700 | DEBUG    | base.py              (112) | configure_curve | Configure curve: *[*]
node2_1_862571c6cde1 | 2019-01-24 10:56:46,703 | INFO     | node.py              (853) | start | Node2 first time running...
node4_1_8a0db220c2a0 | CURVE I: cannot open client HELLO -- wrong server key?
node4_1_8a0db220c2a0 | CURVE I: cannot open client HELLO -- wrong server key?
...
node4_1_8a0db220c2a0 | CURVE I: cannot open client HELLO -- wrong server key?
node1_1_5607204968b3 | CURVE I: cannot open client HELLO -- wrong server key?
...
node1_1_5607204968b3 | CURVE I: cannot open client HELLO -- wrong server key?
node3_1_93ef0a741eb2 | CURVE I: cannot open client HELLO -- wrong server key?
...
node3_1_93ef0a741eb2 | CURVE I: cannot open client HELLO -- wrong server key?
node2_1_862571c6cde1 | CURVE I: cannot open client HELLO -- wrong server key?
...
node2_1_862571c6cde1 | CURVE I: cannot open client HELLO -- wrong server key?
node4_1_8a0db220c2a0 | CURVE I: cannot open client HELLO -- wrong server key?
...
node4_1_8a0db220c2a0 | CURVE I: cannot open client HELLO -- wrong server key?
node1_1_5607204968b3 | CURVE I: cannot open client HELLO -- wrong server key?
...
node1_1_5607204968b3 | CURVE I: cannot open client HELLO -- wrong server key?
node3_1_93ef0a741eb2 | CURVE I: cannot open client HELLO -- wrong server key?
...
node3_1_93ef0a741eb2 | CURVE I: cannot open client HELLO -- wrong server key?
node2_1_862571c6cde1 | CURVE I: cannot open client HELLO -- wrong server key?
...
node2_1_862571c6cde1 | CURVE I: cannot open client HELLO -- wrong server key?
node4_1_8a0db220c2a0 | CURVE I: cannot open client HELLO -- wrong server key?
...
node4_1_8a0db220c2a0 | CURVE I: cannot open client HELLO -- wrong server key?
node1_1_5607204968b3 | CURVE I: cannot open client HELLO -- wrong server key?
...
node1_1_5607204968b3 | CURVE I: cannot open client HELLO -- wrong server key?
node3_1_93ef0a741eb2 | CURVE I: cannot open client HELLO -- wrong server key?
...
node3_1_93ef0a741eb2 | CURVE I: cannot open client HELLO -- wrong server key?
node2_1_862571c6cde1 | CURVE I: cannot open client HELLO -- wrong server key?
...
node2_1_862571c6cde1 | CURVE I: cannot open client HELLO -- wrong server key?
node4_1_8a0db220c2a0 | CURVE I: cannot open client HELLO -- wrong server key?
...
node4_1_8a0db220c2a0 | CURVE I: cannot open client HELLO -- wrong server key?
von-web_1_9cac5775c7b9 | ERROR|indy::services::pool          |           src/services/pool/mod.rs:426 | Pool worker thread finished with error Timeout
von-web_1_9cac5775c7b9 | ERROR|indy::errors::indy            |                 src/errors/indy.rs:68  | Casting error to ErrorCode: Timeout
von-web_1_9cac5775c7b9 | _indy_loop_callback: Function returned error 307
von-web_1_9cac5775c7b9 | Traceback (most recent call last):
von-web_1_9cac5775c7b9 |   File "server.py", line 295, in <module>
von-web_1_9cac5775c7b9 |     loop.run_until_complete(boot())
von-web_1_9cac5775c7b9 |   File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
von-web_1_9cac5775c7b9 |     return future.result()
von-web_1_9cac5775c7b9 |   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
von-web_1_9cac5775c7b9 |     raise self._exception
von-web_1_9cac5775c7b9 |   File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
von-web_1_9cac5775c7b9 |     result = coro.throw(exc)
von-web_1_9cac5775c7b9 |   File "server.py", line 112, in boot
von-web_1_9cac5775c7b9 |     await pool.open()
von-web_1_9cac5775c7b9 |   File "/home/indy/.local/share/virtualenvs/server-8XoupS0v/lib/python3.5/site-packages/von_agent/nodepool.py", line 125, in open
von-web_1_9cac5775c7b9 |     self._handle = await pool.open_pool_ledger(self.name, None)
von-web_1_9cac5775c7b9 |   File "/home/indy/.local/share/virtualenvs/server-8XoupS0v/lib/python3.5/site-packages/indy/pool.py", line 82, in open_pool_ledger
von-web_1_9cac5775c7b9 |     open_pool_ledger.cb)
von-web_1_9cac5775c7b9 |   File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
von-web_1_9cac5775c7b9 |     yield self  # This tells Task to wait for completion.
von-web_1_9cac5775c7b9 |   File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
von-web_1_9cac5775c7b9 |     future.result()
von-web_1_9cac5775c7b9 |   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
von-web_1_9cac5775c7b9 |     raise self._exception
von-web_1_9cac5775c7b9 | indy.error.IndyError: ErrorCode.PoolLedgerTimeout
von_von-web_1_9cac5775c7b9 exited with code 1

**Comment by aTravelingN3rd** [comment]
I don't know if it's relevant but I have this error when running:  ./manage build
 Compiling rusqlcipher v0.14.6
warning: redundant linker flag specified for library `zmq-pw`

   Compiling zmq-pw v0.9.8
warning: unnecessary parentheses around function argument
  --> src/errors/wallet.rs:95:55
   |
95 |         WalletError::CommonError(CommonError::IOError((err)))
   |                                                       ^^^^^ help: remove these parentheses
   |
   = note: #[warn(unused_parens)] on by default

warning: use of deprecated item 'std::env::home_dir': This function's behavior is unexpected and probably not what you want. Consider using the home_dir function from https://crates.io/crates/dirs instead.
 --> src/utils/environment.rs:9:24
  |
9 |         let mut path = env::home_dir().unwrap_or(PathBuf::from("/home/indy"));
  |                        ^^^^^^^^^^^^^
  |
  = note: #[warn(deprecated)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 3m 11s

and the build seems to run only one time, before it was four time (one for each node I suppose)

**Comment by aTravelingN3rd** [comment]
Moved to ubuntu 16.04 and the issue was solved
