### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'Pipfile'

### ISSUE THREAD

**Issue by herveblanc** [IBM-Blockchain-Identity/indy-ssivc-tutorial#7]
~/git/indy-ssivc-tutorial/von-network$ ./manage start
WARNING: The IP variable is not set. Defaulting to a blank string.
WARNING: The IPS variable is not set. Defaulting to a blank string.
Starting von_node3_1 ... done
Starting von_node2_1 ... done
Starting von_node1_1 ... done
Starting von_node4_1 ... done
Starting von_von-web_1 ... done
Attaching to von_node4_1, von_node3_1, von_node2_1, von_node1_1, von_von-web_1
node4_1    | Ledger exists - using...
node4_1    | start_indy_node Node4 9707 9708
node3_1    | Ledger exists - using...
node3_1    | start_indy_node Node3 9705 9706
node2_1    | Ledger exists - using...
node2_1    | start_indy_node Node2 9703 9704
node1_1    | Ledger exists - using...
node1_1    | start_indy_node Node1 9701 9702
von-web_1  | Ledger exists - using...
von-web_1  | Traceback (most recent call last):
von-web_1  |   File "/usr/local/bin/pipenv", line 11, in <module>
von-web_1  |     sys.exit(cli())
von-web_1  |   File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
von-web_1  |     return self.main(*args, **kwargs)
von-web_1  |   File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 697, in main
von-web_1  |     rv = self.invoke(ctx)
von-web_1  |   File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
von-web_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
von-web_1  |   File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
von-web_1  |     return ctx.invoke(self.callback, **ctx.params)
von-web_1  |   File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
von-web_1  |     return callback(*args, **kwargs)
von-web_1  |   File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 637, in run
von-web_1  |     do_run(command=command, args=args, three=three, python=python)
von-web_1  |   File "/usr/local/lib/python3.5/dist-packages/pipenv/core.py", line 2294, in do_run
von-web_1  |     ensure_project(three=three, python=python, validate=False)
von-web_1  |   File "/usr/local/lib/python3.5/dist-packages/pipenv/core.py", line 616, in ensure_project
von-web_1  |     project.touch_pipfile()
von-web_1  |   File "/usr/local/lib/python3.5/dist-packages/pipenv/project.py", line 555, in touch_pipfile
von-web_1  |     with open('Pipfile', 'a'):
von-web_1  | PermissionError: [Errno 13] Permission denied: 'Pipfile'
von_von-web_1 exited with code 1

**Comment by arvind1410** [comment]
I too get the same error. Can You please explain a way for getting over the error?

**Comment by arvind1410** [comment]
Go to your Pipfile and Pipfile.Lock files.
Change the python version to 3.5. The problem is solved now.

**Comment by sunburntcat** [comment]
There may be a bigger issue. I get this same error when running on CentOS. However, I now see that the Dockerfile and README require Ubuntu 16.04 to build. CentOS can't run apt-get and therefore results in Python 3.5 library errors.

**Comment by sunburntcat** [comment]
@arvind1410 Could you describe where the Pipfile and Pipfile.lock files might be and how we can change them within the demo? Also, would the interactive docker be run as: docker run -it von-base  ?

**Comment by sunburntcat** [comment]
The Pipfile and Pipfile.lock files had Python version 3.5 already set at the tops of the files. As a patch, I fixed the permission issue with by adding the following line near the top of von-network/scripts/start_webserver.sh:

find /* -type d | xargs chmod 777 --silent

**Comment by JacobMcConomy** [comment]
@sunburntcat What line number exactly did you edit? I tried this and it changed nothing. Thanks for the help!

**Comment by sunburntcat** [comment]
@JacobMcConomy The command just has to go after the bin/bash header at the top, which would be line 2. It should only fix the Pipfile error. You might still get a von_web exit for other reasons (as is the case with me).
